[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "lrcget"
version = "1.0.0"
description = "personal lrclib api client"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mutagen>=1.47.0",
    "requests>=2.34.2",
]

[project.scripts]
lrcget = "lrcget.cli:main"

[dependency-groups]
dev = []
